website/music/urls.py
from django.conf.urls import url
from . import views

app_name ='music'

urlpatterns = [
# /music/
   url(r'^$',views.index,name="index"),

#/music/717/
   url(r'^(?P<album_id>[0-9]+)/$',views.detail,name ='detail'),

#/music/<album_id>/favourite/
   url(r'^(?P<album_id>[0-9]+)/$',views.favourite,name='favourite'),


]

website/website/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
   url( r'^music/',include('music.urls')),
    url(r'^admin/', admin.site.urls),
]

website/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist=models.CharField(max_length=250)
    album_title=models.CharField(max_length=500)
    genre=models.CharField(max_length=100)
    album_logo =models.CharField(max_length=1000)

    def __str__ (self):
        return self.album_title+'-'+self.artist

class Song (models.Model) :
    album =models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type =models.CharField(max_length=10)
    song_title =models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/music/views.py
from .models import Album,Song
from django.http import Http404
from django.shortcuts import render, get_object_or_404
# Create your views here.
def index(request):
    all_albums =Album.objects.all()
    return render(request,'music/index.html',{'all_albums':all_albums})

def detail(request,album_id):
    album = get_object_or_404(Album ,pk=album_id)
    return render(request,'music/detail.html',{'album':album})

def favourite(request,album_id):
    album = Album.objects.get(pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except(KeyError ,Song.DoesNotExsist):
        return render(request,'music/detail.html',
        {'album':album ,
         'error_message':"you did not select a valid song" })

    else:
        selected_song.is_favourite=True
        selected_song.save()
        return render (request,'music/detail.html',{'album':album})

website/music/templates/music/detail.html
<img src="{{album.album_logo}}">

<h1>{{album.album_title}}</h1>
<h3>{{ album.artist}}</h3>

{% if error_message %}
  <p><strong>{{error_message}}</p>
{% endif %}

<form action ="{% url 'music:favourite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
      <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id}}">
      <label for ="song{{forloop.counter}}">
        {{ song.song_title}}
        {% if song.is_favourite %}
            <img src="https://i.imgur.com/b9b13Rd.png" />
        {% endif %}
      </label> <br>
    {% endfor %}
    <input type="submit" value="Favourite">
</form>

website/music/templates/music/index.html
<!-- loads the path to your static files -->
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />

{% if all_albums %}
 <h3>here </h3>
<ul>
  {% for album in all_albums  %}
<li><a href="{% url 'detail'album.id %}">{{album.album_title}}</a></li>
   {%  endfor %}
</ul>

{% else %}

<h3>Oops!no albums yet </h3>
{% endif %}